# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Suman Ganta
title: Software Architect
email: suman.ganta@gmail.com
website: https://sumanganta.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: suman_ganta
github_username:  suman-ganta
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: sganta
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: sumanganta.com
  icon: fas fa-globe
  url: https://sumanganta.com
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  I am a software engineer with 19 years of experience, specializing in technical architecture, requirements engineering and technical design/implementation primarily in distributed systems architecture and frameworks in Java ecosystem.

  I write substantial amounts of production code most part of my job, and I also prefer the challenge of shaping a system's platform and scaffolding out system prototypes which eventually become production ready. My strength is over-all architecture and crafting solutions to meet requirements rather than heavily concentrated in front-end or back-end.

  Experienced in designing and developing the systems to meet customer, scale, availabilty and operational requirements in the hosted services (cloud) model.

  I subscribe to a pragmatic ideology: software development is ultimately a trade-off, and there is a big difference between doing something well and doing it perfectly. Stable processes, diligent design and quality oversight, competence and transparency is what makes software delivery successful.Quality software systems must not just meet their requirements as they are expressed now, but meet the need as it will exist at the point where the system is actually delivered.

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Apple
        link: https://www.apple.com
        link_text: apple.com
        sub_title: Software Architect
        caption: August 2019 - Present
        quote: >
          Apple media products engineering
        description: | # this will include new lines to allow paragraphs
            Solving content distribution problems at scale.
      - layout: left
        title: Oracle
        link: https://www.oracle.com
        link_text: oracle.com
        sub_title: Software Architect
        caption: April 2012 - Aug 2019
        quote: >
          Business Process orchestration and human workflow platforms
        description: | # this will include new lines to allow paragraphs
            * Designed and developed BPM human workflow enhancements for 11gR1 Oracle Fusion Middleware. These enhancements include editing support for the workflow metadata during runtime to avoid redeployment of the whole workflow upon every modification.
            * Lead Process portal product architecture. Process portal allows completing business process in a very efficient manner. This adds web2.0 collaboration technologies into the process portal to complete any activity in an effective manner.
      - layout: left
        title: Active Endpoints (now Informatica)
        link: https://network.informatica.com/community/informatica-network/products/process_automation/active_vos/
        link_text: activevos.com
        sub_title: Sr Software Architect
        caption: October 2010 - April 2012
        quote: >
          Building ActiveVOS orchestration platform
        description: | # this will include new lines to allow paragraphs
          Some of the critical features I designed and developed to ActiveVOS BPEL engine and SOA platform include:
          * Rich XQuery execution and editing support
          * Custom script function support to BPEL engine
          * Migration infrastructure for running processes
          * Business event processing support
          * OAuth1.x/2.0 client side process level support for ActiveVOS platform
          * Monitoring support for critical parameters of the ActiveVOS platform.
          * Cluster infrastructure migration and improvement.
          * WS-HT spec performance improvements of the implementation.
      - layout: left
        title: Teradyne
        link: https://www.teradyne.com/
        link_text: teradyne.com
        sub_title: Software Architect
        caption: October 2010 - April 2012
        quote: >
          Document management and order management solutions
        description: | # this will include new lines to allow paragraphs
          * Designed eKnowledge solution for Teradyne. This is document management solution for Teradyne to maintain product manuals/driver software etc for their test equipment.
          * Provided architecture for Merlin2.0, an order management solution that tracks part orders for Teradyne test equipments. This replaces a legacy Merlin1.0 system that has many short comings. Designed the solution using OFM 11g/Workflow/Rules
      - layout: left
        title: Oracle
        link: https://www.oracle.com
        link_text: oracle.com
        sub_title: Principal member of technical staff
        caption: Feb 2008 - June 2010
        quote: >
          Business Process orchestration and human workflow platforms
        description: | # this will include new lines to allow paragraphs
          * Designed and developed BPM human workflow enhancements for 11gR1 Oracle Fusion Middleware. These enhancements include editing support for the workflow metadata during runtime to avoid redeployment of the whole workflow upon every modification.
          * Lead Process portal product architecture. Process portal allows completing business process in a very efficient manner. This adds web2.0 collaboration technologies into the process portal to complete any activity in an effective manner.
      - layout: left
        title: Software AG
        link: https://www.softwareag.com
        link_text: softwareag.com
        sub_title: Sr Software Engineer II
        caption: May 2007 - Feb 2008
        quote: >
          Business Process orchestration and human workflow platforms
        description: | # this will include new lines to allow paragraphs
          * Designed the deployment infrastructure to have a common deployment platform for all webMethods suite of products.
          * Worked with JSR88 spec lead to understand the standard and implemented the core infrastructure.
      
      - layout: left
        title: Lexicon Infotech
        link: http://lexiconinfotech.com/
        link_text: lexiconinfotech.com
        sub_title: Software Engineer
        caption: Jan 2003 - Feb 2007
        quote: >
          Lexicon E-Class
        description: | # this will include new lines to allow paragraphs
          * E-Class development

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Jawaharlal Nehru Technological University
        caption: 1997 - 2001
        sub_title: B.Tech Computer Science and Engineering

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
